server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Fulene/ecom-ms-app-config.git
    consul:
      host: 172.17.0.2
      port: 8500
